/* =========================================================
   ICE_TECH — Product catalog & shared data
   Prices in FCFA (XAF) — Cameroon
   ========================================================= */

const CATEGORIES = [
  { id: "rings",     name: "Rings",      sub: "Engagement & signature", glyph: "💍", grad: "grad-rings",     image: "assets/prod-eternity-vvs.png" },
  { id: "necklaces", name: "Necklaces",  sub: "Chains & pendants",      glyph: "📿", grad: "grad-necklaces", image: "assets/prod-cuban-link-necklace.png" },
  { id: "bracelets", name: "Bracelets",  sub: "Tennis & iced bangle",   glyph: "✨", grad: "grad-bracelets", image: "assets/prod-tennis-bracelet.png" },
  { id: "grills",    name: "Grills",     sub: "Custom dental",          glyph: "🦷", grad: "grad-grills",    image: "assets/prod-custom-grill.png" },
  { id: "watches",   name: "Watches",    sub: "Luxury iced-out",        glyph: "⌚", grad: "grad-watches",   image: "assets/prod-iced-watch.png" },
];

const MATERIALS = ["14k Gold", "18k Gold", "White Gold", "VVS Diamonds", "Moissanite"];

const PRODUCTS = [
  {
    id: "eternity-vvs",
    name: "VVS Eternity Ring",
    category: "rings",
    tag: "Engagement",
    glyph: "💍",
    price: 45000,
    compare: 55000,
    badge: "Best-seller",
    rating: 4.9,
    reviews: 128,
    desc: "Brilliant-cut solitaire set with a GRA-certified VVS diamond. Absolute sparkle, hand-set on a solid gold band.",
    materials: ["18k Gold", "White Gold", "VVS Diamonds", "Moissanite"],
    featured: true,
  },
  {
    id: "cuban-link-necklace",
    name: "Cuban Link Chain",
    category: "necklaces",
    tag: "Iced-out",
    glyph: "📿",
    price: 52000,
    compare: 60000,
    badge: "Iconic",
    rating: 5.0,
    reviews: 96,
    desc: "Fully iced pavé Cuban link. The ultimate statement piece — heavy, brilliant and timeless.",
    materials: ["14k Gold", "18k Gold", "VVS Diamonds", "Moissanite"],
    featured: true,
  },
  {
    id: "tennis-bracelet",
    name: "Tennis Bracelet",
    category: "bracelets",
    tag: "Signature",
    glyph: "✨",
    price: 34000,
    compare: 42000,
    badge: "New",
    rating: 4.8,
    reviews: 74,
    desc: "A continuous line of prong-set stones, perfectly calibrated. The very definition of iced elegance.",
    materials: ["14k Gold", "White Gold", "VVS Diamonds", "Moissanite"],
    featured: true,
  },
  {
    id: "custom-grill",
    name: "Custom 8-Tooth Grill",
    category: "grills",
    tag: "Custom",
    glyph: "🦷",
    price: 28000,
    compare: null,
    badge: "Custom",
    rating: 5.0,
    reviews: 51,
    desc: "Custom impression, mirror finish and VVS pavé of your choice. Crafted after a consultation for a perfect fit.",
    materials: ["14k Gold", "18k Gold", "White Gold", "VVS Diamonds", "Moissanite"],
    featured: true,
  },
  {
    id: "iced-watch",
    name: "Iced-Out Glacier Watch",
    category: "watches",
    tag: "Luxury",
    glyph: "⌚",
    price: 55000,
    compare: 65000,
    badge: "Limited edition",
    rating: 4.9,
    reviews: 38,
    desc: "Fully pavé case and bracelet. Automatic movement, permanent shine on the wrist.",
    materials: ["18k Gold", "White Gold", "VVS Diamonds", "Moissanite"],
    featured: true,
  },
  {
    id: "halo-ring",
    name: "Brilliant Halo Ring",
    category: "rings",
    tag: "Engagement",
    glyph: "💍",
    price: 31000,
    compare: null,
    badge: null,
    rating: 4.8,
    reviews: 64,
    desc: "A center stone surrounded by a sparkling halo that amplifies the light from every angle.",
    materials: ["14k Gold", "18k Gold", "White Gold", "Moissanite"],
    featured: false,
  },
  {
    id: "rope-chain",
    name: "Diamond-Cut Rope Chain",
    category: "necklaces",
    tag: "Classic",
    glyph: "📿",
    price: 19000,
    compare: 24000,
    badge: null,
    rating: 4.7,
    reviews: 112,
    desc: "Finely twisted rope link with diamond-cut reflections. Versatile, worn alone or layered.",
    materials: ["14k Gold", "18k Gold", "White Gold"],
    featured: false,
  },
  {
    id: "bangle-bracelet",
    name: "Unisex Iced Bangle",
    category: "bracelets",
    tag: "Signature",
    glyph: "✨",
    price: 15000,
    compare: null,
    badge: null,
    rating: 4.6,
    reviews: 43,
    desc: "A rigid bangle pavé-set on the top face. A touch of minimalist ice for everyday wear.",
    materials: ["14k Gold", "White Gold", "Moissanite"],
    featured: false,
  },
  {
    id: "grill-bottom",
    name: "Bottom 6-Tooth Grill",
    category: "grills",
    tag: "Custom",
    glyph: "🦷",
    price: 22000,
    compare: null,
    badge: null,
    rating: 4.9,
    reviews: 29,
    desc: "A discreet bottom set, finish of your choice. Impression required for optimal comfort.",
    materials: ["14k Gold", "18k Gold", "VVS Diamonds", "Moissanite"],
    featured: false,
  },
  {
    id: "pendant-cross",
    name: "VVS Cross Pendant",
    category: "necklaces",
    tag: "Pendant",
    glyph: "✝️",
    price: 26000,
    compare: 32000,
    badge: null,
    rating: 4.9,
    reviews: 87,
    desc: "A cross fully pavé-set with VVS diamonds, delivered with its matching chain.",
    materials: ["14k Gold", "18k Gold", "White Gold", "VVS Diamonds", "Moissanite"],
    featured: false,
  },
  {
    id: "signet-ring",
    name: "Iced Signet Ring",
    category: "rings",
    tag: "Signature",
    glyph: "💍",
    price: 24000,
    compare: null,
    badge: null,
    rating: 4.7,
    reviews: 33,
    desc: "A modern signet ring with a pavé face. Bold presence, impeccable finish.",
    materials: ["14k Gold", "18k Gold", "White Gold", "Moissanite"],
    featured: false,
  },
  {
    id: "skeleton-watch",
    name: "Gold Skeleton Watch",
    category: "watches",
    tag: "Luxury",
    glyph: "⌚",
    price: 47000,
    compare: null,
    badge: null,
    rating: 4.8,
    reviews: 21,
    desc: "Openworked skeleton dial revealing the movement, pavé bezel. Watchmaking and ice combined.",
    materials: ["18k Gold", "White Gold", "VVS Diamonds"],
    featured: false,
  },
];

const SHIPPING_OPTIONS = [
  { id: "douala-same", label: "Same-day delivery — Douala", sub: "Dedicated courier within 4h, hand-delivered", price: 0, free: true },
  { id: "yaounde-express", label: "Express — Yaoundé", sub: "Secure delivery within 24h", price: 5000, free: false },
];

const PAYMENT_OPTIONS = [
  { id: "mtn-momo", label: "MTN Mobile Money", sub: "Instant payment via MoMo", glyph: '<span class="pay-logo momo">MTN</span>' },
  { id: "orange-money", label: "Orange Money", sub: "Instant payment via OM", glyph: '<span class="pay-logo om">orange</span>' },
  { id: "cod", label: "Cash on delivery", sub: "Cash on receipt (Douala & Yaoundé)", glyph: '<span class="pay-logo cash">CASH</span>' },
];

function formatXAF(n) {
  return new Intl.NumberFormat("en-US").format(n) + " FCFA";
}

function getProduct(id) {
  return PRODUCTS.find((p) => p.id === id);
}
